export const DepartmentsAppointmentTime = {
  GENERAL_PRACTICE: 16,
  OBSTETRICS: 12,
  SURGERY: 18,
  DENTISTRY: 30,
  THERAPY: 15,
  OPHTHALMOLOGY: 18,
  PEDIATRICS: 25,
  CARDIOLOGY: 25,
  NEUROLOGY: 20,
  ENDOCRINOLOGY: 20,
  DERMATOLOGY: 15,
  MENTAL_HEALTH: 30,
};
